name: geoguide
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_map: ^7.0.2
  flutter_compass: ^0.8.1
  rxdart: ^0.28.0
  latlong2: ^0.9.1
  flutter_map_location_marker: ^9.1.1
  geolocator: ^13.0.4
  background_location: ^0.13.0
  flutter_svg: ^2.1.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/imggeoguid.png"
  
# para instalar o novo icone rodar comando: flutter pub get
# flutter pub run flutter_launcher_icons
flutter:
  uses-material-design: true
  assets:
    - assets/compass/
